#!/usr/bin/env python3
"""
OTF/TTF → Adafruit GFX Font Header Converter for TFT_eSPI
v3: Size-adaptive binarization threshold for clean small fonts.
"""
import sys, os
from PIL import Image, ImageFont, ImageDraw

def convert_font(font_path, pixel_size, font_name, output_dir):
    font = ImageFont.truetype(font_path, pixel_size)
    ascent, descent = font.getmetrics()
    FIRST, LAST = 32, 126
    bitmap_bytes, glyphs = [], []
    offset = 0
    canvas_h = ascent + descent + pixel_size

    # Adaptive threshold: smaller fonts need lower threshold
    # to capture anti-aliased edge pixels
    if pixel_size <= 14:
        threshold = 40
    elif pixel_size <= 18:
        threshold = 64
    elif pixel_size <= 24:
        threshold = 80
    else:
        threshold = 100

    for code in range(FIRST, LAST + 1):
        char = chr(code)
        advance = int(round(font.getlength(char)))

        canvas_w = max(advance * 2 + 20, pixel_size * 2)
        img = Image.new('L', (canvas_w, canvas_h), 0)
        draw = ImageDraw.Draw(img)
        draw.text((0, 0), char, font=font, fill=255)

        pixel_bbox = img.getbbox()
        if pixel_bbox is None:
            glyphs.append((offset, 0, 0, advance, 0, 0))
            continue

        pl, pt, pr, pb = pixel_bbox
        w, h = pr - pl, pb - pt
        xOffset = pl
        yOffset = pt - ascent

        cropped = img.crop(pixel_bbox)

        bits = []
        for y in range(h):
            for x in range(w):
                bits.append(1 if cropped.getpixel((x, y)) > threshold else 0)

        gb = []
        for i in range(0, len(bits), 8):
            b = 0
            for j in range(8):
                if i + j < len(bits):
                    b |= bits[i + j] << (7 - j)
            gb.append(b)

        bitmap_bytes.extend(gb)
        glyphs.append((offset, w, h, advance, xOffset, yOffset))
        offset += len(gb)

    y_adv = ascent + descent
    out_path = os.path.join(output_dir, f"{font_name}.h")
    with open(out_path, 'w') as f:
        f.write(gen_header(font_name, bitmap_bytes, glyphs, FIRST, LAST, y_adv))
    return out_path, len(bitmap_bytes), threshold


def gen_header(name, bitmap, glyphs, first, last, y_adv):
    L = []
    L.append(f"// SF Pro Display font: {name}")
    L.append(f"// Auto-generated by otf2gfx.py — include AFTER TFT_eSPI.h")
    L.append(f"#pragma once")
    L.append(f"")
    L.append(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmap), 16):
        L.append("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i+16]) + ",")
    L.append("};")
    L.append("")
    L.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for i, (off, w, h, adv, xo, yo) in enumerate(glyphs):
        c = first + i
        ch = chr(c) if 33 <= c <= 126 else ' '
        L.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {max(0,min(255,adv)):3d}, {max(-128,min(127,int(xo))):4d}, {max(-128,min(127,int(yo))):4d} }},  // '{ch}'")
    L.append("};")
    L.append("")
    L.append(f"const GFXfont {name} PROGMEM = {{")
    L.append(f"  (uint8_t  *){name}Bitmaps,")
    L.append(f"  (GFXglyph *){name}Glyphs,")
    L.append(f"  0x{first:02X}, 0x{last:02X}, {y_adv}")
    L.append("};")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    base = os.path.dirname(os.path.abspath(__file__))
    FONT_DIR = os.path.join(base, "..", "dashboard", "public", "sf-pro-display")
    OUT_DIR  = os.path.join(base, "the_catalyst")

    # Updated font list:
    # - Dropped LightItalic 12 (too thin for 1-bit at small size)
    # - Added Regular 12 as caption font (readable at small size)
    FONTS = [
        ("SFPRODISPLAYREGULAR.OTF",  12, "SFPro_Regular_12"),   # Captions
        ("SFPRODISPLAYREGULAR.OTF",  14, "SFPro_Regular_14"),   # Labels
        ("SFPRODISPLAYMEDIUM.OTF",   16, "SFPro_Medium_16"),    # Body
        ("SFPRODISPLAYBOLD.OTF",     22, "SFPro_Bold_22"),      # Headers
        ("SFPRODISPLAYBOLD.OTF",     32, "SFPro_Bold_32"),      # Hero values
    ]

    print("=" * 60)
    print("  SF Pro Display -> GFX Header (v3: adaptive threshold)")
    print("=" * 60)
    total = 0
    for fn, sz, nm in FONTS:
        p = os.path.join(FONT_DIR, fn)
        if not os.path.exists(p):
            print(f"  X SKIP: {fn}"); continue
        _, nb, thr = convert_font(p, sz, nm, OUT_DIR)
        total += nb
        print(f"  OK {nm:.<30s} {nb:>6,d} bytes ({sz}px, thr={thr})")
    print("-" * 60)
    print(f"  Total: {total:,d} bytes ({total/1024:.1f} KB)")
    print("=" * 60)
